// src/app/layout.tsx (Server-side layout)
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import RootLayoutClient from './RootLayoutClient'; // Import the client-side layout
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RootLayoutClient>{children}</RootLayoutClient> {/* Use client-side layout here */}
      </body>
    </html>
  );
}
