name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main  # Change this if needed
    paths:
      - 'frontend/**'      # Only trigger this workflow if something changes under 'frontend/'
      - '.github/workflows/frontend.yml'
      - '!frontend/README.md' # Exclude certain files

jobs:
  deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
