name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main  # Change this if needed
    paths:
      - 'frontend/**'      # Only trigger this workflow if something changes under 'frontend/'
      - '.github/workflows/frontend.yml'
      - '!frontend/README.md' # Exclude certain files

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 2: Set Environment Variables for Build
      - name: Set Environment Variables for Build
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> frontend/.env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> frontend/.env

      # Step 3: Build Frontend
      - name: Build Frontend
        run: npm run build
          
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 2: Run Tests
      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 2: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Step 3: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
