name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'lambda-code-evaluator-v2/**'      # Only trigger this workflow if something changes under 'frontend/'
      - '!lambda-code-evaluator-v2/README.md' # Exclude certain files

jobs:
  build_and_push:
    defaults:
      run:
        working-directory: lambda-code-evaluator-v2

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/lambda-code-evaluator-v2:latest
