name: Build and Deploy Lambda Microservice Image

on:
  push:
    branches:
      - main
    paths:
      - 'lambda-code-evaluator-v2/**'
      - '!lambda-code-evaluator-v2/README.md'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda-code-evaluator-v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lambda-code-evaluator-v2
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "Building image..."
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo "Pushing image..."
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
