name: Build and Deploy Questions Microservice

on:
  push:
    branches:
      - main
    paths:
      - 'questions/random-questions/**'
      - '!questions/random-questions/README.md'
      - '.github/workflows/lambda-questions-api.yml'

jobs:
  lint-and-format:
    name: Lint and Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Black and Flake8
        run: |
          pip install black flake8

      - name: Run Black (Auto-format)
        run: |
          black questions/random-questions --check

      - name: Run Flake8 (Linting)
        run: |
          flake8 questions/random-questions

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: questions/random-questions
    needs: lint-and-format

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lambda-questions-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building image..."
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo "Pushing image..."
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
      
      - name: Update Lambda Function
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lambda-questions-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name random-questions \
            --image-uri $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
